/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallLog {
  'id' : bigint,
  'customerName' : string,
  'status' : CallStatus,
  'customerPhone' : string,
  'createdAt' : Time,
  'callType' : CallType,
  'customerAddress' : string,
  'requirement' : string,
  'notes' : string,
}
export type CallStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'followUp' : null };
export type CallType = { 'serviceEnquiry' : null } |
  { 'general' : null } |
  { 'salesEnquiry' : null };
export interface DashboardStats {
  'totalOrders' : bigint,
  'activeRentals' : bigint,
  'openServiceJobs' : bigint,
  'openCalls' : bigint,
}
export type OrderType = { 'consumable' : null } |
  { 'machineSale' : null };
export interface RentalAgreement {
  'id' : bigint,
  'customerName' : string,
  'status' : RentalStatus,
  'endDate' : Time,
  'customerPhone' : string,
  'createdAt' : Time,
  'customerAddress' : string,
  'notes' : string,
  'machineSerial' : string,
  'monthlyFee' : bigint,
  'machineType' : string,
  'startDate' : Time,
}
export type RentalStatus = { 'active' : null } |
  { 'upcoming' : null } |
  { 'expired' : null };
export interface SalesOrder {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'orderDate' : Time,
  'orderType' : OrderType,
  'customerAddress' : string,
  'notes' : string,
  'itemName' : string,
  'quantity' : bigint,
}
export interface ServiceJob {
  'id' : bigint,
  'customerName' : string,
  'status' : ServiceJobStatus,
  'assignedTo' : string,
  'issueDescription' : string,
  'customerPhone' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'customerAddress' : string,
  'machineType' : string,
}
export type ServiceJobStatus = { 'delayed' : null } |
  { 'done' : null } |
  { 'inTransit' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCallLog' : ActorMethod<
    [string, string, string, string, CallType, string],
    bigint
  >,
  'createRental' : ActorMethod<
    [string, string, string, string, string, Time, Time, bigint, string],
    bigint
  >,
  'createSalesOrder' : ActorMethod<
    [string, string, string, OrderType, string, bigint, string],
    bigint
  >,
  'createServiceJob' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'deleteCallLog' : ActorMethod<[bigint], undefined>,
  'deleteRental' : ActorMethod<[bigint], undefined>,
  'deleteSalesOrder' : ActorMethod<[bigint], undefined>,
  'deleteServiceJob' : ActorMethod<[bigint], undefined>,
  'getAllCallLogs' : ActorMethod<[], Array<CallLog>>,
  'getAllRentals' : ActorMethod<[], Array<RentalAgreement>>,
  'getAllSalesOrders' : ActorMethod<[], Array<SalesOrder>>,
  'getAllServiceJobs' : ActorMethod<[], Array<ServiceJob>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallsByStatus' : ActorMethod<[CallStatus], Array<CallLog>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getRentalsByStatus' : ActorMethod<[RentalStatus], Array<RentalAgreement>>,
  'getServiceJobsByStatus' : ActorMethod<[ServiceJobStatus], Array<ServiceJob>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'readCallLog' : ActorMethod<[bigint], [] | [CallLog]>,
  'readRental' : ActorMethod<[bigint], [] | [RentalAgreement]>,
  'readSalesOrder' : ActorMethod<[bigint], [] | [SalesOrder]>,
  'readServiceJob' : ActorMethod<[bigint], [] | [ServiceJob]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCallStatus' : ActorMethod<[bigint, CallStatus], undefined>,
  'updateRentalStatus' : ActorMethod<[bigint, RentalStatus], undefined>,
  'updateServiceJob' : ActorMethod<[bigint, ServiceJobStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];