/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallType = IDL.Variant({
  'serviceEnquiry' : IDL.Null,
  'general' : IDL.Null,
  'salesEnquiry' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderType = IDL.Variant({
  'consumable' : IDL.Null,
  'machineSale' : IDL.Null,
});
export const CallStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'followUp' : IDL.Null,
});
export const CallLog = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : CallStatus,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'callType' : CallType,
  'customerAddress' : IDL.Text,
  'requirement' : IDL.Text,
  'notes' : IDL.Text,
});
export const RentalStatus = IDL.Variant({
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
  'expired' : IDL.Null,
});
export const RentalAgreement = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : RentalStatus,
  'endDate' : Time,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'customerAddress' : IDL.Text,
  'notes' : IDL.Text,
  'machineSerial' : IDL.Text,
  'monthlyFee' : IDL.Nat,
  'machineType' : IDL.Text,
  'startDate' : Time,
});
export const SalesOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'orderDate' : Time,
  'orderType' : OrderType,
  'customerAddress' : IDL.Text,
  'notes' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ServiceJobStatus = IDL.Variant({
  'delayed' : IDL.Null,
  'done' : IDL.Null,
  'inTransit' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceJob = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : ServiceJobStatus,
  'assignedTo' : IDL.Text,
  'issueDescription' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'customerAddress' : IDL.Text,
  'machineType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'activeRentals' : IDL.Nat,
  'openServiceJobs' : IDL.Nat,
  'openCalls' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCallLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, CallType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createRental' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createSalesOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, OrderType, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createServiceJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCallLog' : IDL.Func([IDL.Nat], [], []),
  'deleteRental' : IDL.Func([IDL.Nat], [], []),
  'deleteSalesOrder' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceJob' : IDL.Func([IDL.Nat], [], []),
  'getAllCallLogs' : IDL.Func([], [IDL.Vec(CallLog)], ['query']),
  'getAllRentals' : IDL.Func([], [IDL.Vec(RentalAgreement)], ['query']),
  'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
  'getAllServiceJobs' : IDL.Func([], [IDL.Vec(ServiceJob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallsByStatus' : IDL.Func([CallStatus], [IDL.Vec(CallLog)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getRentalsByStatus' : IDL.Func(
      [RentalStatus],
      [IDL.Vec(RentalAgreement)],
      ['query'],
    ),
  'getServiceJobsByStatus' : IDL.Func(
      [ServiceJobStatus],
      [IDL.Vec(ServiceJob)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'readCallLog' : IDL.Func([IDL.Nat], [IDL.Opt(CallLog)], ['query']),
  'readRental' : IDL.Func([IDL.Nat], [IDL.Opt(RentalAgreement)], ['query']),
  'readSalesOrder' : IDL.Func([IDL.Nat], [IDL.Opt(SalesOrder)], ['query']),
  'readServiceJob' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceJob)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCallStatus' : IDL.Func([IDL.Nat, CallStatus], [], []),
  'updateRentalStatus' : IDL.Func([IDL.Nat, RentalStatus], [], []),
  'updateServiceJob' : IDL.Func([IDL.Nat, ServiceJobStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallType = IDL.Variant({
    'serviceEnquiry' : IDL.Null,
    'general' : IDL.Null,
    'salesEnquiry' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderType = IDL.Variant({
    'consumable' : IDL.Null,
    'machineSale' : IDL.Null,
  });
  const CallStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'followUp' : IDL.Null,
  });
  const CallLog = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : CallStatus,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'callType' : CallType,
    'customerAddress' : IDL.Text,
    'requirement' : IDL.Text,
    'notes' : IDL.Text,
  });
  const RentalStatus = IDL.Variant({
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
    'expired' : IDL.Null,
  });
  const RentalAgreement = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : RentalStatus,
    'endDate' : Time,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'customerAddress' : IDL.Text,
    'notes' : IDL.Text,
    'machineSerial' : IDL.Text,
    'monthlyFee' : IDL.Nat,
    'machineType' : IDL.Text,
    'startDate' : Time,
  });
  const SalesOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'orderDate' : Time,
    'orderType' : OrderType,
    'customerAddress' : IDL.Text,
    'notes' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ServiceJobStatus = IDL.Variant({
    'delayed' : IDL.Null,
    'done' : IDL.Null,
    'inTransit' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceJob = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : ServiceJobStatus,
    'assignedTo' : IDL.Text,
    'issueDescription' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'customerAddress' : IDL.Text,
    'machineType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'activeRentals' : IDL.Nat,
    'openServiceJobs' : IDL.Nat,
    'openCalls' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCallLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, CallType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createRental' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createSalesOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, OrderType, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createServiceJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCallLog' : IDL.Func([IDL.Nat], [], []),
    'deleteRental' : IDL.Func([IDL.Nat], [], []),
    'deleteSalesOrder' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceJob' : IDL.Func([IDL.Nat], [], []),
    'getAllCallLogs' : IDL.Func([], [IDL.Vec(CallLog)], ['query']),
    'getAllRentals' : IDL.Func([], [IDL.Vec(RentalAgreement)], ['query']),
    'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
    'getAllServiceJobs' : IDL.Func([], [IDL.Vec(ServiceJob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallsByStatus' : IDL.Func([CallStatus], [IDL.Vec(CallLog)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getRentalsByStatus' : IDL.Func(
        [RentalStatus],
        [IDL.Vec(RentalAgreement)],
        ['query'],
      ),
    'getServiceJobsByStatus' : IDL.Func(
        [ServiceJobStatus],
        [IDL.Vec(ServiceJob)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'readCallLog' : IDL.Func([IDL.Nat], [IDL.Opt(CallLog)], ['query']),
    'readRental' : IDL.Func([IDL.Nat], [IDL.Opt(RentalAgreement)], ['query']),
    'readSalesOrder' : IDL.Func([IDL.Nat], [IDL.Opt(SalesOrder)], ['query']),
    'readServiceJob' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceJob)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCallStatus' : IDL.Func([IDL.Nat, CallStatus], [], []),
    'updateRentalStatus' : IDL.Func([IDL.Nat, RentalStatus], [], []),
    'updateServiceJob' : IDL.Func([IDL.Nat, ServiceJobStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };