/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface SalesOrder {
    id: bigint;
    customerName: string;
    customerPhone: string;
    orderDate: Time;
    orderType: OrderType;
    customerAddress: string;
    notes: string;
    itemName: string;
    quantity: bigint;
}
export interface RentalAgreement {
    id: bigint;
    customerName: string;
    status: RentalStatus;
    endDate: Time;
    customerPhone: string;
    createdAt: Time;
    customerAddress: string;
    notes: string;
    machineSerial: string;
    monthlyFee: bigint;
    machineType: string;
    startDate: Time;
}
export interface ServiceJob {
    id: bigint;
    customerName: string;
    status: ServiceJobStatus;
    assignedTo: string;
    issueDescription: string;
    customerPhone: string;
    createdAt: Time;
    updatedAt: Time;
    customerAddress: string;
    machineType: string;
}
export interface CallLog {
    id: bigint;
    customerName: string;
    status: CallStatus;
    customerPhone: string;
    createdAt: Time;
    callType: CallType;
    customerAddress: string;
    requirement: string;
    notes: string;
}
export interface DashboardStats {
    totalOrders: bigint;
    activeRentals: bigint;
    openServiceJobs: bigint;
    openCalls: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum CallStatus {
    closed = "closed",
    open = "open",
    followUp = "followUp"
}
export enum CallType {
    serviceEnquiry = "serviceEnquiry",
    general = "general",
    salesEnquiry = "salesEnquiry"
}
export enum OrderType {
    consumable = "consumable",
    machineSale = "machineSale"
}
export enum RentalStatus {
    active = "active",
    upcoming = "upcoming",
    expired = "expired"
}
export enum ServiceJobStatus {
    delayed = "delayed",
    done = "done",
    inTransit = "inTransit",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCallLog(customerName: string, customerAddress: string, customerPhone: string, requirement: string, callType: CallType, notes: string): Promise<bigint>;
    createRental(customerName: string, customerAddress: string, customerPhone: string, machineType: string, machineSerial: string, startDate: Time, endDate: Time, monthlyFee: bigint, notes: string): Promise<bigint>;
    createSalesOrder(customerName: string, customerAddress: string, customerPhone: string, orderType: OrderType, itemName: string, quantity: bigint, notes: string): Promise<bigint>;
    createServiceJob(customerName: string, customerAddress: string, customerPhone: string, machineType: string, issueDescription: string, assignedTo: string): Promise<bigint>;
    deleteCallLog(id: bigint): Promise<void>;
    deleteRental(id: bigint): Promise<void>;
    deleteSalesOrder(id: bigint): Promise<void>;
    deleteServiceJob(id: bigint): Promise<void>;
    getAllCallLogs(): Promise<Array<CallLog>>;
    getAllRentals(): Promise<Array<RentalAgreement>>;
    getAllSalesOrders(): Promise<Array<SalesOrder>>;
    getAllServiceJobs(): Promise<Array<ServiceJob>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallsByStatus(status: CallStatus): Promise<Array<CallLog>>;
    getDashboardStats(): Promise<DashboardStats>;
    getRentalsByStatus(status: RentalStatus): Promise<Array<RentalAgreement>>;
    getServiceJobsByStatus(status: ServiceJobStatus): Promise<Array<ServiceJob>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    readCallLog(id: bigint): Promise<CallLog | null>;
    readRental(id: bigint): Promise<RentalAgreement | null>;
    readSalesOrder(id: bigint): Promise<SalesOrder | null>;
    readServiceJob(id: bigint): Promise<ServiceJob | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCallStatus(id: bigint, status: CallStatus): Promise<void>;
    updateRentalStatus(id: bigint, status: RentalStatus): Promise<void>;
    updateServiceJob(id: bigint, status: ServiceJobStatus): Promise<void>;
}
import type { CallLog as _CallLog, CallStatus as _CallStatus, CallType as _CallType, OrderType as _OrderType, RentalAgreement as _RentalAgreement, RentalStatus as _RentalStatus, SalesOrder as _SalesOrder, ServiceJob as _ServiceJob, ServiceJobStatus as _ServiceJobStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCallLog(arg0: string, arg1: string, arg2: string, arg3: string, arg4: CallType, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCallLog(arg0, arg1, arg2, arg3, to_candid_CallType_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCallLog(arg0, arg1, arg2, arg3, to_candid_CallType_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createRental(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Time, arg6: Time, arg7: bigint, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRental(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRental(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createSalesOrder(arg0: string, arg1: string, arg2: string, arg3: OrderType, arg4: string, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalesOrder(arg0, arg1, arg2, to_candid_OrderType_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalesOrder(arg0, arg1, arg2, to_candid_OrderType_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createServiceJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createServiceJob(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServiceJob(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteCallLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallLog(arg0);
            return result;
        }
    }
    async deleteRental(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRental(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRental(arg0);
            return result;
        }
    }
    async deleteSalesOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalesOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalesOrder(arg0);
            return result;
        }
    }
    async deleteServiceJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceJob(arg0);
            return result;
        }
    }
    async getAllCallLogs(): Promise<Array<CallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCallLogs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCallLogs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRentals(): Promise<Array<RentalAgreement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRentals();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRentals();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalesOrders(): Promise<Array<SalesOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesOrders();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesOrders();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServiceJobs(): Promise<Array<ServiceJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceJobs();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceJobs();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallsByStatus(arg0: CallStatus): Promise<Array<CallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallsByStatus(to_candid_CallStatus_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallsByStatus(to_candid_CallStatus_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getRentalsByStatus(arg0: RentalStatus): Promise<Array<RentalAgreement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalsByStatus(to_candid_RentalStatus_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalsByStatus(to_candid_RentalStatus_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceJobsByStatus(arg0: ServiceJobStatus): Promise<Array<ServiceJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceJobsByStatus(to_candid_ServiceJobStatus_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceJobsByStatus(to_candid_ServiceJobStatus_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async readCallLog(arg0: bigint): Promise<CallLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.readCallLog(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readCallLog(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async readRental(arg0: bigint): Promise<RentalAgreement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.readRental(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readRental(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async readSalesOrder(arg0: bigint): Promise<SalesOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.readSalesOrder(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readSalesOrder(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async readServiceJob(arg0: bigint): Promise<ServiceJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.readServiceJob(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readServiceJob(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCallStatus(arg0: bigint, arg1: CallStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallStatus(arg0, to_candid_CallStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallStatus(arg0, to_candid_CallStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRentalStatus(arg0: bigint, arg1: RentalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRentalStatus(arg0, to_candid_RentalStatus_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRentalStatus(arg0, to_candid_RentalStatus_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateServiceJob(arg0: bigint, arg1: ServiceJobStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceJob(arg0, to_candid_ServiceJobStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceJob(arg0, to_candid_ServiceJobStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CallLog_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallLog): CallLog {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CallType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallType): CallType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RentalAgreement_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalAgreement): RentalAgreement {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RentalStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalStatus): RentalStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SalesOrder_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesOrder): SalesOrder {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceJobStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceJobStatus): ServiceJobStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceJob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceJob): ServiceJob {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallLog]): CallLog | null {
    return value.length === 0 ? null : from_candid_CallLog_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RentalAgreement]): RentalAgreement | null {
    return value.length === 0 ? null : from_candid_RentalAgreement_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesOrder]): SalesOrder | null {
    return value.length === 0 ? null : from_candid_SalesOrder_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceJob]): ServiceJob | null {
    return value.length === 0 ? null : from_candid_ServiceJob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _RentalStatus;
    endDate: _Time;
    customerPhone: string;
    createdAt: _Time;
    customerAddress: string;
    notes: string;
    machineSerial: string;
    monthlyFee: bigint;
    machineType: string;
    startDate: _Time;
}): {
    id: bigint;
    customerName: string;
    status: RentalStatus;
    endDate: Time;
    customerPhone: string;
    createdAt: Time;
    customerAddress: string;
    notes: string;
    machineSerial: string;
    monthlyFee: bigint;
    machineType: string;
    startDate: Time;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_RentalStatus_n17(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        customerAddress: value.customerAddress,
        notes: value.notes,
        machineSerial: value.machineSerial,
        monthlyFee: value.monthlyFee,
        machineType: value.machineType,
        startDate: value.startDate
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    customerPhone: string;
    orderDate: _Time;
    orderType: _OrderType;
    customerAddress: string;
    notes: string;
    itemName: string;
    quantity: bigint;
}): {
    id: bigint;
    customerName: string;
    customerPhone: string;
    orderDate: Time;
    orderType: OrderType;
    customerAddress: string;
    notes: string;
    itemName: string;
    quantity: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        customerPhone: value.customerPhone,
        orderDate: value.orderDate,
        orderType: from_candid_OrderType_n22(_uploadFile, _downloadFile, value.orderType),
        customerAddress: value.customerAddress,
        notes: value.notes,
        itemName: value.itemName,
        quantity: value.quantity
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _ServiceJobStatus;
    assignedTo: string;
    issueDescription: string;
    customerPhone: string;
    createdAt: _Time;
    updatedAt: _Time;
    customerAddress: string;
    machineType: string;
}): {
    id: bigint;
    customerName: string;
    status: ServiceJobStatus;
    assignedTo: string;
    issueDescription: string;
    customerPhone: string;
    createdAt: Time;
    updatedAt: Time;
    customerAddress: string;
    machineType: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_ServiceJobStatus_n27(_uploadFile, _downloadFile, value.status),
        assignedTo: value.assignedTo,
        issueDescription: value.issueDescription,
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        customerAddress: value.customerAddress,
        machineType: value.machineType
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _CallStatus;
    customerPhone: string;
    createdAt: _Time;
    callType: _CallType;
    customerAddress: string;
    requirement: string;
    notes: string;
}): {
    id: bigint;
    customerName: string;
    status: CallStatus;
    customerPhone: string;
    createdAt: Time;
    callType: CallType;
    customerAddress: string;
    requirement: string;
    notes: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_CallStatus_n10(_uploadFile, _downloadFile, value.status),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        callType: from_candid_CallType_n12(_uploadFile, _downloadFile, value.callType),
        customerAddress: value.customerAddress,
        requirement: value.requirement,
        notes: value.notes
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    followUp: null;
}): CallStatus {
    return "closed" in value ? CallStatus.closed : "open" in value ? CallStatus.open : "followUp" in value ? CallStatus.followUp : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceEnquiry: null;
} | {
    general: null;
} | {
    salesEnquiry: null;
}): CallType {
    return "serviceEnquiry" in value ? CallType.serviceEnquiry : "general" in value ? CallType.general : "salesEnquiry" in value ? CallType.salesEnquiry : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    upcoming: null;
} | {
    expired: null;
}): RentalStatus {
    return "active" in value ? RentalStatus.active : "upcoming" in value ? RentalStatus.upcoming : "expired" in value ? RentalStatus.expired : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    consumable: null;
} | {
    machineSale: null;
}): OrderType {
    return "consumable" in value ? OrderType.consumable : "machineSale" in value ? OrderType.machineSale : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delayed: null;
} | {
    done: null;
} | {
    inTransit: null;
} | {
    inProgress: null;
}): ServiceJobStatus {
    return "delayed" in value ? ServiceJobStatus.delayed : "done" in value ? ServiceJobStatus.done : "inTransit" in value ? ServiceJobStatus.inTransit : "inProgress" in value ? ServiceJobStatus.inProgress : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RentalAgreement>): Array<RentalAgreement> {
    return value.map((x)=>from_candid_RentalAgreement_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesOrder>): Array<SalesOrder> {
    return value.map((x)=>from_candid_SalesOrder_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceJob>): Array<ServiceJob> {
    return value.map((x)=>from_candid_ServiceJob_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallLog>): Array<CallLog> {
    return value.map((x)=>from_candid_CallLog_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CallStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): _CallStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_CallType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallType): _CallType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RentalStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalStatus): _RentalStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceJobStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceJobStatus): _ServiceJobStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): {
    closed: null;
} | {
    open: null;
} | {
    followUp: null;
} {
    return value == CallStatus.closed ? {
        closed: null
    } : value == CallStatus.open ? {
        open: null
    } : value == CallStatus.followUp ? {
        followUp: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalStatus): {
    active: null;
} | {
    upcoming: null;
} | {
    expired: null;
} {
    return value == RentalStatus.active ? {
        active: null
    } : value == RentalStatus.upcoming ? {
        upcoming: null
    } : value == RentalStatus.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceJobStatus): {
    delayed: null;
} | {
    done: null;
} | {
    inTransit: null;
} | {
    inProgress: null;
} {
    return value == ServiceJobStatus.delayed ? {
        delayed: null
    } : value == ServiceJobStatus.done ? {
        done: null
    } : value == ServiceJobStatus.inTransit ? {
        inTransit: null
    } : value == ServiceJobStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallType): {
    serviceEnquiry: null;
} | {
    general: null;
} | {
    salesEnquiry: null;
} {
    return value == CallType.serviceEnquiry ? {
        serviceEnquiry: null
    } : value == CallType.general ? {
        general: null
    } : value == CallType.salesEnquiry ? {
        salesEnquiry: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    consumable: null;
} | {
    machineSale: null;
} {
    return value == OrderType.consumable ? {
        consumable: null
    } : value == OrderType.machineSale ? {
        machineSale: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
